[[token-controlled-token-circulation]]
== Token-Controlled Token Circulaton (TCTC)

The circulation of tokens comprises three types of principal transactions: mint, transfer, and burn. Depending on the application, various conditions must be satisfied to execute these transactions, e.g., only qualified shops can mint the tokens and only a certain agent can transfer the tokens. The token circulating system mints, transfers, or burns a token only if the control tokens are owned by the participants of the transaction. The circulation control tokens themselves can be any type of token, e.g., a driver's license or a membership certificate of a certain group, and recursively circulated in the token circulating system. This scheme eliminates the need to write complex circulation control in smart contracts for each application, improving the security of the system and reducing development costs.

[[using-token-controller]]
=== Using `TokenController`

Token-controller contracts provides xref:api:access.adoc#AccessControl[`AccessControl`] for implementing TCTC. Its usage is straightforward: for each role that you want to define,
you will create a new _role identifier_ that is used to grant, revoke, and check if an account has that role.

Here's a simple example of using `TokenController` in an xref:tokens.adoc#ERC721[`ERC721` token] to define a 'minter' and 'burner' role, which allows accounts that have it create new tokens and destroy existing tokens by specifying the controll token:

[source,solidity]
----
// contracts/MyToken.sol
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.9;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "./TokenController.sol";

contract MyToken is ERC721, TokenController {
    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant BURNER_ROLE = keccak256("HOLDER_ROLE");

    constructor() ERC721("MyToken", "MTK") {
        // Specifies the deployed contract ID of the control token.
        // This sample contract is deployed on Goerli.
        _grantRoleByToken(MINTER_ROLE, 0xF1e33c646a12F68bC8015b4AED29BB316fA2D593);
        _grantRoleByToken(BURNER_ROLE, 0xcDc6fD5F29E2641f25c90235eDA984f99aA3a1DD);
    }

    function safeMint(address to, uint256 tokenId)
        public onlyHasToken(MINTER_ROLE, msg.sender)
    {
        _safeMint(to, tokenId);
    }

    function burn(uint256 tokenId) 
        public onlyHasToken(BURNER_ROLE, msg.sender) 
    {
        _burn(tokenId);
    }
}
----

[[granting-and-revoking]]
=== Granting and Revoking Roles

This example above uses `_grantRoleByToken`, an `internal` function that is useful when programmatically assigning roles (such as during construction). But what if we later want to grant the 'minter' role to additional accounts?

To grant and revoke roles dynamically, you will need help from the the issuer of the control tokens specified.

